kind: pipeline
type: docker
name: node-14

steps:
- name: test
  image: node:14
  environment:
    URUNGI_TEST_MYSQL: '{ "host": "mariadb", "database": "urungi_tests", "user": "urungi", "password": "urungi" }'
    URUNGI_TEST_PG: '{ "host": "postgres", "database": "urungi_tests", "user": "urungi", "password": "urungi" }'
  commands:
  - npm ci
  - npm test

services:
- name: mariadb
  image: mariadb:10.3
  environment:
    MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    MYSQL_DATABASE: urungi_tests
    MYSQL_USER: urungi
    MYSQL_PASSWORD: urungi
- name: postgres
  image: postgres:9.6
  environment:
    POSTGRES_DB: urungi_tests
    POSTGRES_USER: urungi
    POSTGRES_PASSWORD: urungi

---
kind: pipeline
type: docker
name: node-12

steps:
- name: test
  image: node:12
  environment:
    URUNGI_TEST_MYSQL: '{ "host": "mariadb", "database": "urungi_tests", "user": "urungi", "password": "urungi" }'
    URUNGI_TEST_PG: '{ "host": "postgres", "database": "urungi_tests", "user": "urungi", "password": "urungi" }'
  commands:
  - npm ci
  - npm test

services:
- name: mariadb
  image: mariadb:10.3
  environment:
    MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    MYSQL_DATABASE: urungi_tests
    MYSQL_USER: urungi
    MYSQL_PASSWORD: urungi
- name: postgres
  image: postgres:9.6
  environment:
    POSTGRES_DB: urungi_tests
    POSTGRES_USER: urungi
    POSTGRES_PASSWORD: urungi
