dist: xenial
language: node_js
node_js:
    - 8
    - 10
env:
    matrix:
        - MONGOMS_VERSION=3.4.21
        - MONGOMS_VERSION=3.6.13
        - MONGOMS_VERSION=4.0.10
services:
    - mysql
    - postgresql
addons:
    mariadb: '10.3'
before_install:
    - mysql -e 'CREATE DATABASE urungi_tests'
    - mysql -e 'GRANT ALL ON urungi_tests.* TO urungi@localhost IDENTIFIED BY "urungi"'
    - psql -c 'create database urungi_tests;' -U postgres
    - npm i -g npm
before_script:
    - npx migrate-mongo up
cache: npm
