# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/node:8
      - image: circleci/mongo:3.4
      - image: circleci/mariadb:10.3
        environment:
          MYSQL_DATABASE: urungi_tests
          MYSQL_USER: urungi
          MYSQL_PASSWORD: urungi

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test
